### ISSUE TITLE
Front matter should specify layout:none

### ISSUE THREAD

**Issue by pke** [georgemandis/jekyll-rss-feeds#32]
When using layouts like "default" the rendered feed xml will be wrapped in this layout. Therefore the templates should all contain the 
`layout: none` front matter.

**Comment by georgemandis** [comment]
Hi @pke

I think I used to have ‘layout: none’ specified in an earlier version of this, but removed it because it created other problems for people and this approach turned out to be better. But that’s just my memory and be easily wrong. I’ll be able to check in a couple days.

Does the current version without frontmatter use the ‘default’ template for you? If so, what version of Jekyll are you using? And is it possible that’s a comfort setting somewhere?

**Comment by pke** [comment]
It is only a problem when one specified a default layout in the `_config.yml` it seems. So feel free to close it but maybe add a little note to the readme?

**Comment by georgemandis** [comment]
That's a good call. I'll something to the README and close this out once I've done that.

Thanks for the catch and suggestion!
